# Generated by Django 5.2.14 on 2026-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TL', 'Team lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
